name: '1. Build Builder Image'

on:
  workflow_dispatch: # 手动触发
  push:
    paths:
      - 'scripts/Dockerfile' # 当 Dockerfile 变化时自动触发

permissions:
  packages: write

env:
  CONTAINER_IMAGE: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42

jobs:
  build_and_push_image:
    # 关键修改：在原生的 arm64 runner 上运行
    runs-on: ubuntu-24.04-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up QEMU 不再需要，因为我们是原生构建
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push builder container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scripts/Dockerfile
          push: true
          tags: ${{ env.CONTAINER_IMAGE }}
          # 关键修改：指定构建 arm64 平台
          platforms: linux/arm64