name: '2. Build Fedora for Nabu'

on:
  push:
    branches:
      - alpha
    paths:
      - 'scripts/2_create_rootfs.sh'
      - 'scripts/3_create_esp.sh'
      - 'scripts/4_create_release.sh'
      - .github/workflows/2-build-fedora-nabu.yml
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 为了创建 Release

env:
  CONTAINER_IMAGE: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42
  ROOTFS_NAME: fedora-42-nabu-rootfs.img
  ESP_NAME: esp.img

jobs:
  # setup_runner 作业不再需要，已删除

  create_rootfs_and_esp:
    # 关键修改：在原生的 arm64 runner 上运行
    runs-on: ubuntu-24.04-arm64
    # 不再需要 needs: setup_runner
    container:
      # 这个镜像是上一步构建的 arm64 镜像，完美匹配
      image: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create aarch64 rootfs
        run: |
          cp ./scripts/2_create_rootfs.sh ./2_create_rootfs.sh
          chmod +x 2_create_rootfs.sh
          ./2_create_rootfs.sh

      - name: Create ESP image
        run: |
          cp ./scripts/3_create_esp.sh ./3_create_esp.sh
          chmod +x 3_create_esp.sh
          ./3_create_esp.sh

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-artifact
          path: ./${{ env.ROOTFS_NAME }}

      - name: Upload ESP image artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp-artifact
          path: ./${{ env.ESP_NAME }}

  create_release:
    # 关键修改：在原生的 arm64 runner 上运行
    runs-on: ubuntu-24.04-arm64
    needs: create_rootfs_and_esp
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release and Upload Assets
        run: |
          cp ./scripts/4_create_release.sh ./4_create_release.sh
          chmod +x 4_create_release.sh
          ./4_create_release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}