name: Build Fedora 42 for Mi Pad 5 (nabu)

on:
  workflow_dispatch: # 允许手动触发

env:
  CONTAINER_IMAGE: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42
  ROOTFS_NAME: fedora-42-nabu-rootfs.tar.gz
  ESP_NAME: esp.img

jobs:
  # 步骤一：构建一个用于后续构建的 Fedora 42 容器镜像
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push builder container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scripts/Dockerfile
          push: true
          tags: ${{ env.CONTAINER_IMAGE }}
          platforms: linux/amd64

  # 步骤二：在容器中制作 aarch64 rootfs
  create_rootfs:
    runs-on: ubuntu-latest
    needs: build_container
    container:
      image: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create aarch64 rootfs
        run: |
          chmod +x ./scripts/2_create_rootfs.sh
          ./scripts/2_create_rootfs.sh
      
      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: rootfs-artifact
          path: ./${{ env.ROOTFS_NAME }}

  # 步骤三：利用 rootfs 制作 ESP 镜像
  create_esp_image:
    runs-on: ubuntu-latest
    needs: create_rootfs
    container:
      image: ghcr.io/${{ github.repository_owner }}/fedora-nabu-builder:42
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download rootfs artifact
        uses: actions/download-artifact@v4
        with:
          name: rootfs-artifact
          path: .

      - name: Create ESP image
        run: |
          chmod +x ./scripts/3_create_esp.sh
          ./scripts/3_create_esp.sh

      - name: Upload ESP image artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp-artifact
          path: ./${{ env.ESP_NAME }}

  # 步骤四：创建 Release 并上传镜像文件
  create_release:
    runs-on: ubuntu-latest
    needs: [create_rootfs, create_esp_image]
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release and Upload Assets
        run: |
          chmod +x ./scripts/4_create_release.sh
          ./scripts/4_create_release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
